

esphome:
  name: servo_smart_switch
  platform: ESP8266
  board: d1
  includes:
    - ServoSmartSwitch.h
    
wifi:
  ssid: !secret ssid
  password: !secret wifiPassword

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

light:
- platform: custom
  lambda: |-
    auto light_out = new ServoSmartSwitch();
    App.register_component(light_out);
    return {light_out};
  lights:
    - name: "Smart Switch"